apiVersion: 1
policies:
  - orgId: 1
    receiver: default-webhook
    group_by: ['alertname','job']
    group_wait: 30s
    group_interval: 2m
    repeat_interval: 2h

    # --- FUTURO: activar ruteo por severidad (email) ---
    # routes:
    #   - receiver: ops-email
    #     object_matchers:
    #       - ['severity', '=', 'critical']
