apiVersion: 1
groups:
  - orgId: 1
    name: Infra / Targets
    folder: Observability
    interval: 1m
    rules:
      - uid: target-down
        title: Target down
        condition: B
        for: 5m
        data:
          # A: query (Prometheus)
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }   # 5m
            datasourceUid: "prometheus"
            model:
              refId: "A"
              editorMode: "code"
              expr: "min_over_time(up[5m])"
              instant: false
              range: true
              intervalMs: 60000
              maxDataPoints: 43200
              legendFormat: ""
          # B: classic condition (expression)
          - refId: B
            relativeTimeRange: { from: 0, to: 0 }
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "classic_conditions"
              conditions:
                - evaluator: { type: lt, params: [1] }
                  operator: { type: and }
                  query: { params: ["A"] }
                  reducer: { type: last }
        labels:
          severity: warning
        annotations:
          summary: "Target abajo: {{ $labels.job }} {{ $labels.instance }}"
          description: "up == 0 por al menos 5m"

      - uid: scrape-slow
        title: Scrape duration p95 > 1s
        condition: B
        for: 5m
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: "prometheus"
            model:
              refId: "A"
              editorMode: "code"
              expr: "histogram_quantile(0.95, sum(rate(scrape_duration_seconds_bucket[5m])) by (le, job))"
              instant: false
              range: true
              intervalMs: 60000
              maxDataPoints: 43200
              legendFormat: ""
          - refId: B
            relativeTimeRange: { from: 0, to: 0 }
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "classic_conditions"
              conditions:
                - evaluator: { type: gt, params: [1] }
                  operator: { type: and }
                  query: { params: ["A"] }
                  reducer: { type: last }
        labels:
          severity: warning
        annotations:
          summary: "Scrape p95 alto en {{ $labels.job }}"
          description: "p95 > 1s durante 5m"

  - orgId: 1
    name: App / Phoenix
    folder: Phoenix
    interval: 1m
    rules:
      - uid: phoenix-high-cpu
        title: Phoenix CPU alta (>80%)
        condition: B
        for: 5m
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: "prometheus"
            model:
              refId: "A"
              editorMode: "code"
              expr: "avg_over_time(cpu_usage_percent{job=\"phoenix\"}[5m])"
              instant: false
              range: true
              intervalMs: 60000
              maxDataPoints: 43200
              legendFormat: ""
          - refId: B
            relativeTimeRange: { from: 0, to: 0 }
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "classic_conditions"
              conditions:
                - evaluator: { type: gt, params: [80] }
                  operator: { type: and }
                  query: { params: ["A"] }
                  reducer: { type: last }
        labels:
          severity: warning
        annotations:
          summary: "CPU alta en Phoenix"
          description: "Promedio 5m > 80%"

      - uid: phoenix-mem-rss
        title: Phoenix RSS > 500 MB
        condition: B
        for: 10m
        data:
          - refId: A
            relativeTimeRange: { from: 600, to: 0 }   # 10m
            datasourceUid: "prometheus"
            model:
              refId: "A"
              editorMode: "code"
              expr: "avg_over_time(process_resident_memory_bytes{job=\"phoenix\"}[10m]) / 1024 / 1024"
              instant: false
              range: true
              intervalMs: 60000
              maxDataPoints: 43200
              legendFormat: ""
          - refId: B
            relativeTimeRange: { from: 0, to: 0 }
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "classic_conditions"
              conditions:
                - evaluator: { type: gt, params: [500] }
                  operator: { type: and }
                  query: { params: ["A"] }
                  reducer: { type: last }
        labels:
          severity: warning
        annotations:
          summary: "Memoria alta en Phoenix"
          description: "RSS > 500 MB durante 10m"

      - uid: phoenix-throttles
        title: Rate limiter throttles detectados
        condition: B
        for: 5m
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: "prometheus"
            model:
              refId: "A"
              editorMode: "code"
              expr: "increase(rate_limiter_throttles_total{job=\"phoenix\"}[5m])"
              instant: false
              range: true
              intervalMs: 60000
              maxDataPoints: 43200
              legendFormat: ""
          - refId: B
            relativeTimeRange: { from: 0, to: 0 }
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "classic_conditions"
              conditions:
                - evaluator: { type: gt, params: [0] }
                  operator: { type: and }
                  query: { params: ["A"] }
                  reducer: { type: last }
        labels:
          severity: warning
        annotations:
          summary: "Throttles en Phoenix"
          description: "Hubo throttles en los últimos 5m"

  - orgId: 1
    name: DB / Capacidad
    folder: Database
    interval: 1m
    rules:
      - uid: db-disk-85
        title: Uso de disco DB > 85%
        condition: B
        for: 5m
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: "prometheus"
            model:
              refId: "A"
              editorMode: "code"
              expr: "max_over_time(database_disk_usage_ratio[5m]) * 100"
              instant: false
              range: true
              intervalMs: 60000
              maxDataPoints: 43200
              legendFormat: ""
          - refId: B
            relativeTimeRange: { from: 0, to: 0 }
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "classic_conditions"
              conditions:
                - evaluator: { type: gt, params: [85] }
                  operator: { type: and }
                  query: { params: ["A"] }
                  reducer: { type: last }
        labels:
          severity: critical
        annotations:
          summary: "Uso de disco alto"
          description: "database_disk_usage_ratio > 85% durante 5m"

      - uid: db-insertions-blocked
        title: Insertions bloqueadas (DB)
        condition: B
        for: 1m
        data:
          - refId: A
            relativeTimeRange: { from: 60, to: 0 }
            datasourceUid: "prometheus"
            model:
              refId: "A"
              editorMode: "code"
              expr: "database_insertions_blocked"
              instant: false
              range: true
              intervalMs: 60000
              maxDataPoints: 43200
              legendFormat: ""
          - refId: B
            relativeTimeRange: { from: 0, to: 0 }
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "classic_conditions"
              conditions:
                - evaluator: { type: gt, params: [0] }
                  operator: { type: and }
                  query: { params: ["A"] }
                  reducer: { type: last }
        labels:
          severity: critical
        annotations:
          summary: "Insertions bloqueadas"
          description: "database_insertions_blocked=1"
